const ADD_USER_MEDIA = 'ADD_USER_MEDIA'
const AUTH_LOADING_SPINNER_START = 'AUTH_LOADING_SPINNER_START'
const AUTH_LOADING_SPINNER_STOP = 'AUTH_LOADING_SPINNER_STOP'
const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
const UPDATE_AUTH_DATA = 'UPDATE_AUTH_DATA'
const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA'
const NEW_USER_CREATED = 'NEW_USER_CREATED'
const CLEAR_NEW_USER = 'CLEAR_NEW_USER'
const LOGOUT_USER = 'LOGOUT_USER'
const DATA_LOADING_SPINNER_START = 'DATA_LOADING_SPINNER_START'
const DATA_LOADING_SPINNER_STOP = 'DATA_LOADING_SPINNER_STOP'

export {
  ADD_USER_MEDIA,
  AUTH_LOADING_SPINNER_START,
  AUTH_LOADING_SPINNER_STOP,
  SET_AUTH_ERROR,
  CLEAR_AUTH_ERROR,
  UPDATE_AUTH_DATA,
  UPDATE_PROFILE_DATA,
  NEW_USER_CREATED,
  CLEAR_NEW_USER,
  LOGOUT_USER,
  DATA_LOADING_SPINNER_START,
  DATA_LOADING_SPINNER_STOP
}
